site_name: "Yunye He (贺 云野)"
site_author: HE Yunye
edit_uri: ""
copyright: ""
theme:
  name: material
  features:
    - navigation.tabs
  font:
    code: Roboto Mono
    text: Roboto
  palette:
    primary: white
    accent: white
  logo: assets/gwaslab.png
  favicon: assets/gwaslab.png

nav:
    - Home: index.md
    - Publications: publications.md
    - Teaching: teaching.md


markdown_extensions:
  - toc:
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

plugins:
  - mkdocs-jupyter
  - search
